In [9]:
import numpy as np
a = np.array([[1,2],[3,4],[5,6]])
for i,j in enumerate(a):
    print(i,j)
print(a)

np.sum(a[:,:],axis=0)

0 [1 2]
1 [3 4]
2 [5 6]
[[1 2]
 [3 4]
 [5 6]]


array([ 9, 12])

In [18]:
b = np.array([[7,8]])
c = np.array([[9,10,11]]) 
f=np.append(c,c,axis=0)
e = np.array([1,10,10])
f // e


array([[9, 1, 1],
       [9, 1, 1]], dtype=int32)

In [23]:
int(0.99)

0

In [2]:
a=[]
for i in a:
    print(i[0])