In [1]:
import numpy as np
a = np.array([[1,2],[3,4],[5,6]])
print(a)
print(a[:,0])
print(np.where(a[:,0] == 5)[0][0])

[[1 2]
 [3 4]
 [5 6]]
[1 3 5]
2


In [2]:
b = np.array([[7,8]])
np.r_[a, b]

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [1]:
def f(**kwargs):
    print(kwargs)

In [3]:
f(i=1,j=2)

{'i': 1, 'j': 2}
